apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefile
  namespace: $NAMESPACE
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 20Gi