SUBSCRIPTIONID="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"   #ID da Assinatura
RESOURCEGROUP="IDM"                                     #Assinatura
ENVIRONMENT="Prod"                                      #ambiente
AKSNAME="$RESOURCEGROUP-$ENVIRONMENT"                   #nome do serviço AKS
NODECOUNT="2"                                           #numero de nós desejados
MINCOUNT="2"                                            #numero minimo de nós
MAXCOUNT="5"                                            #Numero maximo de nós
VMSIZE="Standard_DS2_v2"                                #tipo da VM
USERVM="centos"                                         #usuário a criar nas VMs
SSHKEY="~/.ssh/id_rsa.pub"                              #chave ssh publica a adicionar nas VMs
K8SVERSION="1.14.8"                                     #versão do kubernetes a ser usada. (Consulte disponiveis `az aks get-versions`)
PROJECT="idmproj"                                       #Descrição sem expressões regulares: ^[a-z][a-z0-9-]{1,61}[a-z0-9]$.
AKSPublicIPName="publiciplb$PROJECT"                    #Nome do IP publico AKS ingress. (Letras minusculas e traços apenas)  
SERVICEPRINCIPAL="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" #Necessario para clusters de dev, onde não temos permissão total
CLIENTSECRET="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"     #Necessario para clusters de dev, onde não temos permissão total
PUBLUCIPNAME="IDM-Prod-PublicIP"                        #Nome do recurso IP publico a ser criado na Azure
DNSNAME="idmprod"                                       #Prefixo DNS
STORAGEACCOUNTNAME="idmstoragekeycloak"                 #Nome do recurso storage account a ser criado na azure
LOCATION="eastus2"                                      #Local a ser usado para a criação dos recursos
AKSSHARENAME="themes"                                   #Nome do container storage a sr criado para uso dos pods 
NAMESPACE="idm"                                         #Namespace a ser criada no Kubernetes